"use client";

import { useActionState, useState, useTransition } from "react";
import { confirmTotpEnrollment, startTotpEnrollment, verifyMfaLogin, type EnrollState } from "@/app/(auth)/actions";
import { errorsFor, Field, FormMessage, SubmitButton } from "@/components/auth/form-parts";
import { initialFormState } from "@/lib/validation/auth";

export function MfaLoginForm({ next }: { next?: string }) {
  const [state, action] = useActionState(verifyMfaLogin, initialFormState);
  return (
    <form action={action} noValidate className="flex flex-col gap-4">
      <FormMessage state={state} />
      {next && <input type="hidden" name="next" value={next} />}
      <Field name="code" label="6-digit code" inputMode="numeric" autoComplete="one-time-code" errors={errorsFor("code", state, {})} />
      <SubmitButton>Verify</SubmitButton>
    </form>
  );
}

export function EnrollTotp() {
  const [setup, setSetup] = useState<EnrollState | null>(null);
  const [pending, startTransition] = useTransition();

  if (!setup?.factorId) {
    return (
      <div className="flex flex-col gap-3">
        {setup?.status === "error" && <FormMessage state={setup} />}
        <button
          type="button"
          className="btn btn-primary self-start"
          disabled={pending}
          onClick={() => startTransition(async () => setSetup(await startTotpEnrollment()))}
        >
          {pending ? "Please wait…" : "Turn on two-factor login"}
        </button>
      </div>
    );
  }
  return <ConfirmTotp setup={setup} />;
}

// Mounted once setup has started, so the form state begins with the new factor.
function ConfirmTotp({ setup }: { setup: EnrollState }) {
  const [state, action] = useActionState(confirmTotpEnrollment, setup);

  if (state.status === "success") {
    return (
      <p role="status" className="notice notice-ok">
        {state.message}
      </p>
    );
  }

  return (
    <div className="flex flex-col gap-4">
      <ol className="list-decimal pl-5 text-sm">
        <li>Open an authenticator app such as Google Authenticator, Microsoft Authenticator or 1Password.</li>
        <li>Scan this code, or type the key below.</li>
        <li>Enter the 6-digit code the app shows.</li>
      </ol>
      {/* The QR code is an SVG data URL generated by Supabase Auth. */}
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img src={setup.qr} alt="QR code for your authenticator app" width={180} height={180} className="rounded-xl border-2 border-ink bg-white p-2" />
      <p className="text-xs text-muted">
        Key: <code className="font-mono text-sm break-all text-ink select-all">{setup.secret}</code>
      </p>
      <form action={action} noValidate className="flex flex-col gap-4">
        <FormMessage state={state} />
        <Field name="code" label="6-digit code" inputMode="numeric" autoComplete="one-time-code" errors={errorsFor("code", state, {})} />
        <SubmitButton>Confirm and turn on</SubmitButton>
      </form>
    </div>
  );
}
